# -*- coding: utf-8 -*-
"""3Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIT8qfYHk8J097nnb_qaj-jNPdyVJsd-

BLOQUE 1: INSTALACIONES
"""

!pip install -q kaggle pandas numpy matplotlib seaborn
!pip install -q transformers torch
!pip install -q sentence-transformers chromadb
!pip install -q scikit-learn
!pip install -q tensorflow keras
!pip install -q langchain-mistralai

print("✅ Instalaciones completadas")

"""BLOQUE 2: IMPORTACIONES"""

import os
import json
import zipfile
import re
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Para modelos de ML
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Para LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

# Para DistilBERT
from transformers import pipeline

# Para embeddings y vectorstore
from sentence_transformers import SentenceTransformer
import chromadb

# Para Mistral (única importación de LangChain que funciona)
from langchain_mistralai import ChatMistralAI

from google.colab import userdata

print("✅ Importaciones completadas")

"""BLOQUE 3: CONFIGURACIÓN INICIAL"""

N_MUESTRA_DATASET = 10000
N_CORPUS_RAG = 1500
RANDOM_STATE = 42
MAX_PALABRAS = 5000
MAX_LONGITUD = 200
EPOCAS_LSTM = 5

print(f"✅ Configuración cargada")
print(f"   Muestra dataset: {N_MUESTRA_DATASET}")
print(f"   Corpus RAG: {N_CORPUS_RAG}")
print(f"   Épocas LSTM: {EPOCAS_LSTM}")

"""BLOQUE 4: CARGAR DATASET (KAGGLE)"""

KAGGLE_USERNAME = userdata.get("KAGGLE_USERNAME")
KAGGLE_KEY = userdata.get("KAGGLE_KEY")

if not KAGGLE_USERNAME or not KAGGLE_KEY:
    raise ValueError("❌ Faltan credenciales Kaggle")

os.makedirs("/root/.kaggle", exist_ok=True)
with open("/root/.kaggle/kaggle.json", "w") as f:
    json.dump({"username": KAGGLE_USERNAME, "key": KAGGLE_KEY}, f)
os.chmod("/root/.kaggle/kaggle.json", 0o600)

!kaggle datasets download -d snap/amazon-fine-food-reviews

with zipfile.ZipFile("amazon-fine-food-reviews.zip", "r") as zip_ref:
    zip_ref.extractall("amazon_reviews")

df_original = pd.read_csv("amazon_reviews/Reviews.csv")
print(f"✅ Dataset cargado: {df_original.shape[0]} filas, {df_original.shape[1]} columnas")
print(df_original.head())

"""BLOQUE 5: AGENTE 1 - NORMALIZADOR (limpieza de datos)"""

class AgenteNormalizador:
    """Agente 1: Limpieza y normalización de datos"""

    def __init__(self, dataframe, n_muestra=10000):
        self.df = dataframe.copy()
        self.n_muestra = n_muestra

    def limpiar_texto(self, texto):
        """Limpieza básica de texto"""
        if not isinstance(texto, str):
            return ""
        texto = texto.lower()
        texto = re.sub(r'\d+', '', texto)
        texto = re.sub(r'[^\w\s]', '', texto)
        texto = re.sub(r'\s+', ' ', texto).strip()
        return texto

    def ejecutar(self):
        print("\n" + "="*50)
        print("🤖 AGENTE 1: NORMALIZADOR")
        print("="*50)

        # Reducir muestra
        if len(self.df) > self.n_muestra:
            self.df = self.df.sample(n=self.n_muestra, random_state=RANDOM_STATE)
            print(f"📊 Muestra reducida a: {self.df.shape}")

        # Eliminar duplicados
        antes = len(self.df)
        self.df = self.df.drop_duplicates()
        print(f"🗑️ Duplicados eliminados: {antes - len(self.df)}")

        # Manejar valores nulos
        self.df["Summary"] = self.df["Summary"].fillna("")
        self.df["Text"] = self.df["Text"].fillna("")

        # Crear reseña completa
        self.df["FullReview"] = self.df["Summary"] + ". " + self.df["Text"]

        # Limpiar texto
        self.df["CleanedReview"] = self.df["FullReview"].apply(self.limpiar_texto)

        # Eliminar reseñas vacías
        self.df = self.df[self.df["CleanedReview"].str.strip() != ""]

        # Crear target (Score 1-2=negativo, 4-5=positivo, eliminar 3)
        self.df = self.df[self.df["Score"] != 3]
        self.df["Sentiment"] = self.df["Score"].apply(lambda x: 1 if x >= 4 else 0)

        # Balancear clases
        positivos = self.df[self.df["Sentiment"] == 1]
        negativos = self.df[self.df["Sentiment"] == 0]
        n_min = min(len(positivos), len(negativos))

        self.df_balanceado = pd.concat([
            positivos.sample(n=n_min, random_state=RANDOM_STATE),
            negativos.sample(n=n_min, random_state=RANDOM_STATE)
        ]).sample(frac=1, random_state=RANDOM_STATE).reset_index(drop=True)

        print(f"\n✅ Dataset balanceado: {self.df_balanceado.shape}")
        print(f"   Positivos: {len(self.df_balanceado[self.df_balanceado['Sentiment']==1])}")
        print(f"   Negativos: {len(self.df_balanceado[self.df_balanceado['Sentiment']==0])}")

        # Visualización
        plt.figure(figsize=(10, 4))
        plt.subplot(1, 2, 1)
        sns.countplot(data=self.df_balanceado, x="Sentiment")
        plt.title("Distribución de Sentimientos")
        plt.xticks([0, 1], ["NEGATIVO", "POSITIVO"])

        plt.subplot(1, 2, 2)
        sns.countplot(data=self.df_balanceado, x="Score")
        plt.title("Distribución de Puntuaciones")
        plt.show()

        return self.df_balanceado

# Ejecutar Agente 1
agente1 = AgenteNormalizador(df_original, n_muestra=N_MUESTRA_DATASET)
dataset_limpio = agente1.ejecutar()

"""BLOQUE 6: PREPARAR DATOS PARA MODELOS"""

X = dataset_limpio["CleanedReview"].values
y = dataset_limpio["Sentiment"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

print(f"📊 Datos de entrenamiento: {len(X_train)}")
print(f"📊 Datos de prueba: {len(X_test)}")

# Tokenización para LSTM
tokenizer = Tokenizer(num_words=MAX_PALABRAS, oov_token='<OOV>')
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LONGITUD, padding='post', truncating='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LONGITUD, padding='post', truncating='post')

print(f"✅ Embeddings configurados")
print(f"   Vocabulario tamaño: {len(tokenizer.word_index)}")
