# -*- coding: utf-8 -*-
"""3Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIT8qfYHk8J097nnb_qaj-jNPdyVJsd-

BLOQUE 1: INSTALACIONES
"""

!pip install -q kaggle pandas numpy matplotlib seaborn
!pip install -q transformers torch
!pip install -q sentence-transformers chromadb
!pip install -q scikit-learn
!pip install -q tensorflow keras
!pip install -q langchain-mistralai

print("✅ Instalaciones completadas")

"""BLOQUE 2: IMPORTACIONES"""

import os
import json
import zipfile
import re
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Para modelos de ML
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Para LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

# Para DistilBERT
from transformers import pipeline

# Para embeddings y vectorstore
from sentence_transformers import SentenceTransformer
import chromadb

# Para Mistral (única importación de LangChain que funciona)
from langchain_mistralai import ChatMistralAI

from google.colab import userdata

print("✅ Importaciones completadas")

"""BLOQUE 3: CONFIGURACIÓN INICIAL"""

N_MUESTRA_DATASET = 10000
N_CORPUS_RAG = 1500
RANDOM_STATE = 42
MAX_PALABRAS = 5000
MAX_LONGITUD = 200
EPOCAS_LSTM = 5

print(f"✅ Configuración cargada")
print(f"   Muestra dataset: {N_MUESTRA_DATASET}")
print(f"   Corpus RAG: {N_CORPUS_RAG}")
print(f"   Épocas LSTM: {EPOCAS_LSTM}")

"""BLOQUE 4: CARGAR DATASET (KAGGLE)"""

KAGGLE_USERNAME = userdata.get("KAGGLE_USERNAME")
KAGGLE_KEY = userdata.get("KAGGLE_KEY")

if not KAGGLE_USERNAME or not KAGGLE_KEY:
    raise ValueError("❌ Faltan credenciales Kaggle")

os.makedirs("/root/.kaggle", exist_ok=True)
with open("/root/.kaggle/kaggle.json", "w") as f:
    json.dump({"username": KAGGLE_USERNAME, "key": KAGGLE_KEY}, f)
os.chmod("/root/.kaggle/kaggle.json", 0o600)

!kaggle datasets download -d snap/amazon-fine-food-reviews

with zipfile.ZipFile("amazon-fine-food-reviews.zip", "r") as zip_ref:
    zip_ref.extractall("amazon_reviews")

df_original = pd.read_csv("amazon_reviews/Reviews.csv")
print(f"✅ Dataset cargado: {df_original.shape[0]} filas, {df_original.shape[1]} columnas")
print(df_original.head())
