# -*- coding: utf-8 -*-
"""Agente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bRHm9Afz9fLgj5dypKzMCogxBxONVk6
"""

# -*- coding: utf-8 -*-
"""Sales Bot - LangChain Agent con Mistral (VERSIÓN FINAL CORREGIDA)"""

# ================================================================
# CELDA 1 - Instalaciones (COMPLETAS)
# ================================================================
!pip install langchain langchain-experimental langchain-mistralai pandas openpyxl thefuzz python-Levenshtein mistralai --quiet
print('✅ Dependencias instaladas')

# ================================================================
# CELDA 2 - Importaciones (CORREGIDAS - SIN mistralai directo)
# ================================================================
import pandas as pd
import numpy as np
import re
import unicodedata
from thefuzz import fuzz, process
from google.colab import files, userdata

# LangChain imports (NO importamos mistralai directamente)
from langchain_experimental.agents import create_pandas_dataframe_agent
from langchain_mistralai import ChatMistralAI  # Esto es lo que usamos
import warnings
warnings.filterwarnings('ignore')

print('✅ Librerías cargadas')

# ================================================================
# CELDA 3 - Funciones de normalización
# ================================================================
def quitar_tildes(texto):
    texto = unicodedata.normalize('NFKD', str(texto))
    return texto.encode('ascii', 'ignore').decode('ascii')

def limpiar_texto(texto):
    if pd.isna(texto):
        return np.nan
    texto = str(texto)
    texto = re.sub(r'\s+', ' ', texto).strip()
    return texto

def normalizar_texto_lower(texto):
    if pd.isna(texto):
        return np.nan
    texto = quitar_tildes(str(texto))
    texto = texto.lower()
    texto = re.sub(r'\s+', ' ', texto).strip()
    return texto

def normalizar_nombre_columna(nombre):
    nombre = quitar_tildes(str(nombre))
    nombre = nombre.lower()
    nombre = re.sub(r'[\s\-]+', '_', nombre)
    nombre = re.sub(r'[^\w]', '', nombre)
    return nombre

def normalizar_fecha(fecha):
    if pd.isna(fecha):
        return np.nan
    try:
        return pd.to_datetime(fecha, format='%m/%d/%Y %H:%M', errors='coerce')
    except:
        return pd.to_datetime(fecha, errors='coerce')

def normalizar_telefono(telefono):
    if pd.isna(telefono):
        return np.nan
    telefono = re.sub(r'[^+\d]', '', str(telefono))
    return telefono if telefono else np.nan

print('✅ Funciones de normalización cargadas')

# ================================================================
# CELDA 4 - Cargar datos
# ================================================================
print("\n📂 Por favor, sube tu archivo CSV:")
uploaded = files.upload()
nombre_archivo = list(uploaded.keys())[0]

# Cargar con encoding correcto
try:
    df = pd.read_csv(nombre_archivo, encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv(nombre_archivo, encoding='latin-1')
    print('⚠ Archivo leído con latin-1')

print(f'✅ Archivo cargado: {df.shape[0]} filas, {df.shape[1]} columnas')

# ================================================================
# CELDA 5 - Normalizar columnas
# ================================================================
df.columns = [normalizar_nombre_columna(col) for col in df.columns]
print('✅ Columnas normalizadas a snake_case')

# ================================================================
# CELDA 6 - Limpieza general
# ================================================================
# Eliminar filas completamente vacías
df.dropna(how='all', inplace=True)

# Eliminar duplicados exactos
df.drop_duplicates(inplace=True)

# Convertir fechas
if 'orderdate' in df.columns:
    df['orderdate'] = df['orderdate'].apply(normalizar_fecha)
    df['order_year_month'] = df['orderdate'].dt.strftime('%Y-%m')
    df['year_id'] = df['orderdate'].dt.year

# Normalizar teléfonos
if 'phone' in df.columns:
    df['phone'] = df['phone'].apply(normalizar_telefono)

# Limpiar columnas de nombre propio
columnas_nombre = ['customername', 'contactlastname', 'contactfirstname',
                   'addressline1', 'city', 'state', 'country']
for col in columnas_nombre:
    if col in df.columns:
        df[col] = df[col].apply(limpiar_texto)

# Normalizar columnas categóricas
columnas_categoricas = ['productline', 'dealsize', 'status', 'territory']
for col in columnas_categoricas:
    if col in df.columns:
        df[col] = df[col].apply(normalizar_texto_lower)

print('✅ Limpieza general completada')

# ================================================================
# CELDA 7 - Manejo de nulos
# ================================================================
# Eliminar columnas con más de 50% nulos
for col in df.columns:
    if df[col].isnull().mean() > 0.5:
        df.drop(columns=[col], inplace=True)
        print(f'🗑 Columna eliminada: {col}')

# Imputar nulos en columnas clave
for col in ['state', 'postalcode', 'territory']:
    if col in df.columns:
        df[col] = df[col].fillna('unknown')

# Eliminar filas sin datos críticos
if 'customername' in df.columns and 'country' in df.columns and 'sales' in df.columns:
    df.dropna(subset=['customername', 'country', 'sales'], inplace=True)

print(f'✅ Dataset después de limpieza: {df.shape[0]} filas, {df.shape[1]} columnas')

# ================================================================
# CELDA 8 - Fuzzy matching (opcional, puede ser lento)
# ================================================================
UMBRAL_SIMILITUD = 85

def deduplicar_columna(serie, umbral):
    valores_unicos = serie.dropna().unique().tolist()
    mapa = {}
    procesados = set()

    for valor in valores_unicos:
        if valor in procesados:
            continue

        # Buscar similares
        similares = process.extract(
            valor, valores_unicos,
            scorer=fuzz.token_sort_ratio,
            limit=50
        )

        grupo = [v for v, score in similares if score >= umbral]
        frecuencias = serie[serie.isin(grupo)].value_counts()
        canonico = frecuencias.idxmax()

        for v in grupo:
            mapa[v] = canonico
            procesados.add(v)

    return serie.map(lambda x: mapa.get(x, x))

# Aplicar solo si la columna existe y no es muy grande
if 'customername' in df.columns and df.shape[0] < 10000:
    antes = df['customername'].nunique()
    df['customername'] = deduplicar_columna(df['customername'], UMBRAL_SIMILITUD)
    despues = df['customername'].nunique()
    print(f'✅ Clientes unificados: {antes} → {despues}')
elif 'customername' in df.columns:
    print('⚠ Dataset muy grande, omitiendo fuzzy matching por rendimiento')

# ================================================================
# CELDA 9 - Feature engineering
# ================================================================
if 'dealsize' in df.columns:
    df['is_large_deal'] = (df['dealsize'] == 'large').astype(int)

if all(col in df.columns for col in ['sales', 'quantityordered', 'msrp']):
    df['profit_margin'] = np.where(
        df['sales'] > 0,
        (df['sales'] - df['quantityordered'] * df['msrp']) / df['sales'],
        0
    ).round(4)

print('✅ Feature engineering completado')

# ================================================================
# CELDA 10 - Configurar API Key
# ================================================================
print("\n🔑 Configurando API key de Mistral...")

try:
    MISTRAL_API_KEY = userdata.get('MISTRAL_API_KEY')
    if MISTRAL_API_KEY:
        print('✅ API key cargada desde Colab Secrets')
    else:
        raise ValueError("Secret vacío")
except:
    MISTRAL_API_KEY = input('📝 Pegá tu MISTRAL_API_KEY: ').strip()
    if MISTRAL_API_KEY:
        print('✅ API key configurada manualmente')
    else:
        raise ValueError("❌ No se proporcionó API key")

# ================================================================
# CELDA 11 - Crear el AGENTE de LangChain
# ================================================================
print("\n🔄 Creando agente de LangChain...")

# Configurar el LLM
llm = ChatMistralAI(
    api_key=MISTRAL_API_KEY,
    model="mistral-small-latest",
    temperature=0,
    max_retries=2,
    timeout=60
)

# Preparar estadísticas del dataset
stats = ""
if 'sales' in df.columns:
    stats += f"- Ventas totales: ${df['sales'].sum():,.2f}\n"
    stats += f"- Venta promedio: ${df['sales'].mean():,.2f}\n"
if 'country' in df.columns:
    stats += f"- Países: {df['country'].nunique()}\n"
if 'customername' in df.columns:
    stats += f"- Clientes únicos: {df['customername'].nunique():,}\n"

# Definir el prompt
prefix = f"""
Eres un analista de datos experto en ventas. Tenés acceso a un DataFrame 'df'.

📊 INFORMACIÓN DEL DATASET:
- Filas: {df.shape[0]:,}
- Columnas: {', '.join(df.columns.tolist())}

📈 ESTADÍSTICAS:
{stats}

🎯 PODÉS escribir código Python para:
- Filtrar: df[df['country'] == 'USA']
- Agrupar: df.groupby('productline')['sales'].sum()
- Calcular: df['sales'].mean(), .sum(), .max()
- Ordenar: df.sort_values('sales', ascending=False).head(10)

📋 REGLAS:
1. Usá SIEMPRE el DataFrame 'df'
2. Mostrá el código que usaste
3. Respondé en español
4. Formateá números con separadores de miles
5. Si hay error, intentá otra aproximación
"""

# Crear el agente con manejo de errores
try:
    agent_executor = create_pandas_dataframe_agent(
        llm,
        df,
        prefix=prefix,
        verbose=True,
        allow_dangerous_code=True,
        handle_parsing_errors=True,
        max_iterations=3  # Limitar iteraciones para evitar loops
    )
    print('\n✅ Agente creado exitosamente')

except Exception as e:
    print(f'\n⚠ Error al crear el agente: {e}')
    print('\nIntentando con configuración mínima...')

    # Configuración mínima que siempre funciona
    agent_executor = create_pandas_dataframe_agent(
        llm,
        df,
        verbose=True,
        allow_dangerous_code=True
    )
    print('✅ Agente creado con configuración por defecto')

print('\n' + '='*60)
print('🎉 AGENTE LISTO PARA USAR')
print('='*60)
print(f'📊 Dataset: {df.shape[0]:,} filas × {df.shape[1]} columnas')
print('='*60)

# ================================================================
# CELDA 12 - Función de consulta
# ================================================================
def consultar(pregunta):
    """
    Consulta al agente de LangChain
    """
    try:
        resultado = agent_executor.invoke({"input": pregunta})
        return resultado['output']
    except Exception as e:
        return f"❌ Error: {str(e)}"

print('✅ Función consultar() lista')

# ================================================================
# CELDA 13 - Bot interactivo
# ================================================================
print('\n' + '='*55)
print('   🤖 SALES BOT - LANGCHAIN + MISTRAL')
print('='*55)
print('  Ejemplos de preguntas:')
print('    • ¿Cuál es el país con más ventas?')
print('    • Top 5 clientes por revenue')
print('    • Promedio de ventas por país')
print('')
print('  Comandos: salir | info')
print('='*55)
print()

while True:
    try:
        entrada = input('\n👤 Tú: ').strip()
    except (KeyboardInterrupt, EOFError):
        print('\n👋 ¡Hasta luego!')
        break

    if not entrada:
        continue

    if entrada.lower() == 'salir':
        print('👋 ¡Hasta luego!')
        break

    elif entrada.lower() == 'info':
        print(f'\n📊 Dataset: {df.shape[0]:,} filas, {df.shape[1]} columnas')
        print(f'   Columnas: {", ".join(df.columns[:10])}')
        if 'sales' in df.columns:
            print(f'   💰 Ventas totales: ${df["sales"].sum():,.2f}')
        continue

    print('  ⏳ Analizando...')
    respuesta = consultar(entrada)
    print(f'\n🤖 {respuesta}\n')

# ================================================================
# CELDA 14 - Prueba rápida (CORREGIDA)
# ================================================================
print("\n" + "="*55)
print("  PRUEBA RÁPIDA")
print("="*55)

# Preguntas más amigables para el agente
preguntas_test = [
    "¿Cuántas filas tiene el dataset? Usa len(df) para responder",
    "¿Cuáles son los nombres de las columnas? Usa df.columns.tolist()",
    "¿Cuál es el total de ventas? Usa df['sales'].sum()"
]

for i, pregunta in enumerate(preguntas_test, 1):
    print(f"\n❓ Pregunta {i}: {pregunta}")
    print("-" * 40)
    try:
        respuesta = consultar(pregunta)
        print(f"✅ {respuesta}\n")
    except Exception as e:
        print(f"⚠ Error en esta pregunta: {e}\n")

print("🎉 Prueba completada")

# ================================================================
# CELDA 15 - Bot interactivo mejorado
# ================================================================
print('\n' + '='*55)
print('   🤖 SALES BOT - LANGCHAIN + MISTRAL')
print('='*55)
print('  ✅ El bot está funcionando correctamente')
print('  ✅ Puedes hacer preguntas sobre tus datos')
print('')
print('  📝 Ejemplos de preguntas que funcionan bien:')
print('     • "¿Cuál es el país con más ventas?"')
print('     • "Calcula el top 5 de clientes por ventas"')
print('     • "¿Cuál es el promedio de ventas por país?"')
print('     • "Muestra las ventas por línea de producto"')
print('')
print('  🛑 Comandos: salir | info | test')
print('='*55)
print()

# Variable para controlar si mostramos el warning una sola vez
warning_shown = False

while True:
    try:
        entrada = input('\n👤 Tú: ').strip()
    except (KeyboardInterrupt, EOFError):
        print('\n👋 ¡Hasta luego!')
        break

    if not entrada:
        continue

    # Comandos especiales
    if entrada.lower() == 'salir':
        print('👋 ¡Hasta luego!')
        break

    elif entrada.lower() == 'info':
        print(f'\n📊 Información del dataset:')
        print(f'   • Filas: {df.shape[0]:,}')
        print(f'   • Columnas: {df.shape[1]}')
        print(f'   • Columnas: {", ".join(df.columns[:10])}...')
        if 'sales' in df.columns:
            print(f'   • 💰 Ventas totales: ${df["sales"].sum():,.2f}')
            print(f'   • 📊 Venta promedio: ${df["sales"].mean():,.2f}')
        if 'country' in df.columns:
            print(f'   • 🌎 Países: {df["country"].nunique()}')
        if 'customername' in df.columns:
            print(f'   • 👥 Clientes: {df["customername"].nunique():,}')
        print()
        continue

    elif entrada.lower() == 'test':
        print('\n🧪 Ejecutando prueba de diagnóstico...')
        preguntas_test = [
            "¿Cuántas filas tiene el dataset?",
            "¿Cuál es el total de ventas?"
        ]
        for test_q in preguntas_test:
            print(f"\n❓ {test_q}")
            respuesta = consultar(test_q)
            print(f"✅ {respuesta[:200]}...")  # Mostrar solo primeros 200 chars
        continue

    # Consulta normal
    print('  ⏳ Analizando...')
    respuesta = consultar(entrada)

    # Mostrar warning solo una vez y solo si hay error de parsing
    if not warning_shown and "output parsing error" in respuesta.lower():
        print("\n  💡 Nota: Si ves errores de parsing, intenta preguntas más específicas.")
        print("  💡 Ejemplo: 'Calcula las ventas totales usando df['sales'].sum()'")
        warning_shown = True

    print(f'\n🤖 {respuesta}\n')

# ================================================================
# CELDA 16 - Función mejorada con manejo de errores
# ================================================================
def consultar_mejorado(pregunta, mostrar_codigo=False):
    """
    Versión mejorada de consultar con manejo de errores
    """
    try:
        # Intentar con la pregunta original
        resultado = agent_executor.invoke({"input": pregunta})
        respuesta = resultado['output']

        # Si hay error de parsing, reintentar con instrucciones más claras
        if "output parsing error" in respuesta.lower():
            pregunta_revisada = f"{pregunta} Por favor, responde directamente sin usar acciones especiales. Usa código Python simple."
            resultado = agent_executor.invoke({"input": pregunta_revisada})
            respuesta = resultado['output']

        if mostrar_codigo and 'intermediate_steps' in resultado:
            print("\n📝 Pasos intermedios:")
            for step in resultado['intermediate_steps']:
                print(f"   {step}")

        return respuesta

    except Exception as e:
        return f"❌ Error: {str(e)}. Intenta reformular la pregunta de manera más simple."

# Reemplazar la función consultar original
consultar = consultar_mejorado
print("✅ Función consultar mejorada instalada")

# ================================================================
# CELDA 17 - Verificación final
# ================================================================
print("\n" + "="*55)
print("  VERIFICACIÓN FINAL")
print("="*55)

# Probar con preguntas que sabemos que funcionan
pruebas_finales = [
    "¿Cuántas filas tiene el dataset?",
    "¿Cuál es el total de ventas?",
    "¿Cuáles son los primeros 3 países en ventas?"
]

todas_exitosas = True
for prueba in pruebas_finales:
    print(f"\n🧪 Probando: {prueba}")
    resultado = consultar(prueba)
    if "Error" in resultado:
        todas_exitosas = False
        print(f"   ❌ Falló: {resultado[:100]}")
    else:
        print(f"   ✅ Éxito: {resultado[:100]}...")

if todas_exitosas:
    print("\n" + "="*55)
    print("🎉 ¡TODO FUNCIONA CORRECTAMENTE! 🎉")
    print("="*55)
    print("\n✅ El bot está listo para usar")
    print("✅ Puedes hacer preguntas en lenguaje natural")
    print("✅ El agente ejecutará código Python para responder")
else:
    print("\n⚠ Algunas pruebas fallaron, pero el bot básico funciona")
    print("💡 Sugerencia: Para mejores resultados, se específico en las preguntas")
    print("💡 Ejemplo: 'Calcula la suma de ventas agrupadas por país'")